package main

/*
// RENAME THIS FILE TO config.go AND UNCOMMENT ALL CODE IN THIS FILE WHEN YOU
// BUILD THE APPLICATION IT HAS BEEN GIT IGNORED TO HIDE ANY SERVER
// DETAIL CONSTANT SUCH AS IP'S AND PORTS
const DEBUG = true
 */
